# Generated by Django 5.1.3 on 2024-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_ordermenudetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
